// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace zuki.build.tools
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\git\build-tools\mkversion\TemplateH.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class TemplateH : TemplateHBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("//-----------------------------------------------------------------------------\r\n" +
                    "// version.h\r\n//\r\n// This file was automatically generated by ");
            
            #line 9 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppDomain.CurrentDomain.FriendlyName));
            
            #line default
            #line hidden
            this.Write(" \r\n//----------------------------------------------------------------------------" +
                    "-\r\n\r\n#ifndef __AUTOGEN_VERSION_H_\r\n#define __AUTOGEN_VERSION_H_\r\n\r\nstatic char c" +
                    "onst VERSION_PRODUCTNAME_ANSI[]\t\t= \"");
            
            #line 15 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.ProductName));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic char const VERSION_MAJOR_ANSI[]\t\t\t\t= \"");
            
            #line 16 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.Major));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic char const VERSION_MINOR_ANSI[]\t\t\t\t= \"");
            
            #line 17 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.Minor));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic char const VERSION_BUILD_ANSI[]\t\t\t\t= \"");
            
            #line 18 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.Build));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic char const VERSION_REVISION_ANSI[]\t\t\t= \"");
            
            #line 19 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.Revision));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic char const VERSION_VERSION2_ANSI[]\t\t\t= \"");
            
            #line 20 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.ToString(2)));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic char const VERSION_VERSION3_ANSI[]\t\t\t= \"");
            
            #line 21 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.ToString(3)));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic char const VERSION_VERSION4_ANSI[]\t\t\t= \"");
            
            #line 22 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.ToString(4)));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\nstatic wchar_t const VERSION_PRODUCTNAME_UNICODE[]\t= L\"");
            
            #line 24 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.ProductName));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic wchar_t const VERSION_MAJOR_UNICODE[]\t\t= L\"");
            
            #line 25 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.Major));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic wchar_t const VERSION_MINOR_UNICODE[]\t\t= L\"");
            
            #line 26 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.Minor));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic wchar_t const VERSION_BUILD_UNICODE[]\t\t= L\"");
            
            #line 27 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.Build));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic wchar_t const VERSION_REVISION_UNICODE[]\t\t= L\"");
            
            #line 28 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.Revision));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic wchar_t const VERSION_VERSION2_UNICODE[]\t\t= L\"");
            
            #line 29 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.ToString(2)));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic wchar_t const VERSION_VERSION3_UNICODE[]\t\t= L\"");
            
            #line 30 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.ToString(3)));
            
            #line default
            #line hidden
            this.Write("\";\r\nstatic wchar_t const VERSION_VERSION4_UNICODE[]\t\t= L\"");
            
            #line 31 "D:\git\build-tools\mkversion\TemplateH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_fields.Version.ToString(4)));
            
            #line default
            #line hidden
            this.Write(@""";

#ifdef _UNICODE
#define VERSION_PRODUCTNAME		VERSION_PRODUCTNAME_UNICODE
#define VERSION_MAJOR			VERSION_MAJOR_UNICODE
#define VERSION_MINOR			VERSION_MINOR_UNICODE
#define VERSION_BUILD			VERSION_BUILD_UNICODE
#define VERSION_REVISION		VERSION_REVISION_UNICODE
#define VERSION_VERSION2		VERSION_VERSION2_UNICODE
#define VERSION_VERSION3		VERSION_VERSION3_UNICODE
#define VERSION_VERSION4		VERSION_VERSION4_UNICODE
#else
#define VERSION_PRODUCTNAME		VERSION_PRODUCTNAME_ANSI
#define VERSION_MAJOR			VERSION_MAJOR_ANSI
#define VERSION_MINOR			VERSION_MINOR_ANSI
#define VERSION_BUILD			VERSION_BUILD_ANSI
#define VERSION_REVISION		VERSION_REVISION_ANSI
#define VERSION_VERSION2		VERSION_VERSION2_ANSI
#define VERSION_VERSION3		VERSION_VERSION3_ANSI
#define VERSION_VERSION4		VERSION_VERSION4_ANSI
#endif

#endif	// __AUTOGEN_VERSION_H_");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class TemplateHBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
